name: 'compile-minify'
description: 'Minify python code'
runs:
  using: 'composite'
  steps:
    - run: |
        pip install --no-cache-dir compile-minifier
        compileminify run
        sed -i '1 i\**/*.py' .dockerignore
      shell: bash
