name: 'deployment'
description: 'Deploy with ansible'
inputs:
  inventory:
    description: 'Inventory - [staging, next, prod]'
    required: true
  app:
    description: 'App to deploy'
    required: true
  vault-pass:
    descritpion: 'Ansible vault password'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        if [[ "${{ inputs.inventory }}" == "prod" ]]; then
          TAG=latest
        else
          TAG=kubernetes-latest
        fi
        docker run \
        --pull always \
        --rm \
        -e ANSIBLE_VAULT_PASSWD="${{ inputs.vault-pass }}" \
        --entrypoint="./deploy.sh" \
        docker-registry.bimdata.io/bimdata/deployment:$TAG \
        "${{ inputs.inventory }}" "${{ inputs.app }}" "deploy" "true"
      shell: bash
