name: 'get docker tag'
description: 'Get docker and ansible tag to deploy'
inputs:
  branch:
    description: 'Git branch'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.branch }}
      shell: bash
    - id: tag
      run: |
        if [[ ${{ inputs.branch }} == 'refs/heads/develop' ]]; then
          echo "tag=staging" >> $GITHUB_ENV
          echo "rollback_tag=rollback-staging" >> $GITHUB_ENV
        elif [[ ${{ inputs.branch }} == 'refs/heads/release' ]]; then
          echo "tag=next" >> $GITHUB_ENV
          echo "rollback_tag=rollback-next" >> $GITHUB_ENV
        elif [[ ${{ inputs.branch }} == 'refs/heads/master' ]] || [[ ${{ inputs.branch }} == 'refs/heads/main' ]]; then
          echo "tag=prod" >> $GITHUB_ENV
          echo "rollback_tag=rollback-prod" >> $GITHUB_ENV
        elif [[ ${{ inputs.branch }} == 'refs/heads/feature/github-actions' ]]; then
          echo "tag=staging" >> $GITHUB_ENV
        fi
      shell: bash
