name: 'build-image'
description: 'Build an image with ansible'
inputs:
  inventory:
    description: 'Inventory - [staging, next, prod]'
    required: true
  app:
    description: 'App to build'
    required: true
  vault-pass:
    descritpion: 'Ansible vault password'
    required: true
runs:
  using: 'composite'

  steps:
    - run: |
        DOCKER_NAME=$(docker container create \
        --env ANSIBLE_VAULT_PASSWD="${{ inputs.vault-pass }}" \
        --entrypoint="./build.sh" \
        --rm \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        docker-registry.bimdata.io/bimdata/deployment:latest \
        "${{ inputs.inventory }}" "${{ inputs.app }}" "deploy" "$CONTEXT_DIR")
        docker container cp $PWD $DOCKER_NAME:$CONTEXT_DIR
        docker start --attach $DOCKER_NAME
      shell: bash
      env:
        CONTEXT_DIR: /var/repo